services:
  chat_client:
    image: xianwei042/client:v1
    tty: true
    stdin_open: true
    volumes:
      - ${PWD}/client.conf:/xianwei/conf/client.conf:ro
      - type: bind
        source: ${PWD}/data
        target: /xianwei/data
        read_only: false
        bind: 
          create_host_path: true
      - type: bind
        source: ${HOME}/
        target: /xianwei/file
