/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `chat_session`;

CREATE TABLE `chat_session` (
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `session_id` varchar(60) NOT NULL,
  `chat_type` tinyint NOT NULL,
  `session_name` varchar(60) NULL,
  `session_owner` varchar(60) NULL)
 ENGINE=InnoDB;

CREATE UNIQUE INDEX `session_id_i`
  ON `chat_session` (`session_id`);

CREATE UNIQUE INDEX `session_name_i`
  ON `chat_session` (`session_name`);

CREATE INDEX `session_owner_i`
  ON `chat_session` (`session_owner`);

