/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `file`;

CREATE TABLE `file` (
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `user_id` varchar(60) NOT NULL,
  `session_id` varchar(60) NOT NULL,
  `file_name` varchar(60) NOT NULL,
  `file_id` varchar(60) NOT NULL,
  `file_sum` varchar(255) NOT NULL)
 ENGINE=InnoDB;

CREATE INDEX `user_id_i`
  ON `file` (`user_id`);

CREATE INDEX `session_id_i`
  ON `file` (`session_id`);

CREATE INDEX `file_name_i`
  ON `file` (`file_name`);

CREATE INDEX `file_id_i`
  ON `file` (`file_id`);

CREATE INDEX `file_sum_i`
  ON `file` (`file_sum`);

