/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `friend_apply`;

CREATE TABLE `friend_apply` (
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `event_id` varchar(64) NOT NULL,
  `user_id` varchar(64) NOT NULL,
  `peer_id` varchar(64) NOT NULL)
 ENGINE=InnoDB;

CREATE UNIQUE INDEX `event_id_i`
  ON `friend_apply` (`event_id`);

CREATE INDEX `user_id_i`
  ON `friend_apply` (`user_id`);

CREATE INDEX `peer_id_i`
  ON `friend_apply` (`peer_id`);

