/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `relation`;

CREATE TABLE `relation` (
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `user_id` varchar(64) NOT NULL,
  `peer_id` varchar(64) NOT NULL,
  `session_id` varchar(64) NOT NULL,
  `if_ignore` tinyint NOT NULL)
 ENGINE=InnoDB;

CREATE INDEX `user_id_i`
  ON `relation` (`user_id`);

CREATE INDEX `peer_id_i`
  ON `relation` (`peer_id`);

CREATE INDEX `session_id_i`
  ON `relation` (`session_id`);

