/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `session_apply`;

CREATE TABLE `session_apply` (
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `event_id` varchar(64) NOT NULL,
  `session_id` varchar(64) NOT NULL,
  `user_id` varchar(64) NOT NULL)
 ENGINE=InnoDB;

CREATE UNIQUE INDEX `event_id_i`
  ON `session_apply` (`event_id`);

CREATE INDEX `session_id_i`
  ON `session_apply` (`session_id`);

CREATE INDEX `user_id_i`
  ON `session_apply` (`user_id`);

